version: 2.1

default-node-image: &default-node-image
  docker:
    - image: cimg/node:18.12.0

jobs:
  build:
    <<: *default-node-image
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: build
          command: npm run build
      - save_cache:
          paths: [./node_modules]
          key: app-dependencies-{{ checksum "package-lock.json" }}

  test:
    <<: *default-node-image
    steps:
      - checkout
      - restore_cache:
          key: app-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: run unit tests
          command: npm run test

  lint:
    <<: *default-node-image
    steps:
      - checkout
      - restore_cache:
          key: app-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: lint
          command: |
            npm run format
            npm run lint

  build-docker-image:
    <<: *default-node-image
    steps:
      - checkout
      - restore_cache:
          key: app-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: login into dockerhub
          command: docker login --username $DOCKER_USER --password $DOCKER_PW
      - run:
          name: build docker image
          command: docker build -t capstone .
      - run:
          name: tag docker image
          command: docker tag capstone ht2314/capstone:${CIRCLE_WORKFLOW_ID:0:7}
      - run:
          name: push docker image
          command: docker push ht2314/capstone:${CIRCLE_WORKFLOW_ID:0:7}

workflows:
  default:
    jobs:
      - build
      - test:
          requires: [build]
      - lint:
          requires: [build]
      - build-docker-image:
          requires: [lint, test]
