version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.3

default-node-image: &default-node-image
  docker:
    - image: cimg/node:18.12.0

commands:
  install-kubectl:
    description: resusable command to install kubectl
    steps:
      - run: 
          name: install kubectl
          command: |
            curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.7/2022-06-29/bin/linux/amd64/kubectL
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
            echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
            kubectl version --short --client

  install-eksctl:
    description: resusable command to install eksctl
    steps:
      - run:
          name: install eksctl
          command: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
  
  destroy-cluster:
    description: destroy cluster if there is a failure in creation
    steps:
      - run:
          name: destroy cluster
          when: on_fail
          command: |
            eksctl delete cluster --region=us-east-1 --name=capstone-project

jobs:
  build:
    <<: *default-node-image
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: build
          command: npm run build
      - save_cache:
          paths: [./node_modules, .svelte-kit]
          key: app-dependencies-{{ .Environment.CIRCLE_WORKFLOW_ID }}

  test:
    <<: *default-node-image
    steps:
      - checkout
      - restore_cache:
          key: app-dependencies-{{ .Environment.CIRCLE_WORKFLOW_ID }}
      - run:
          name: run unit tests
          command: npm run test

  lint:
    <<: *default-node-image
    steps:
      - checkout
      - restore_cache:
          key: app-dependencies-{{ .Environment.CIRCLE_WORKFLOW_ID }}
      - run:
          name: lint
          command: |
            npm run format
            npm run lint

  build-docker-image:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - restore_cache:
          key: app-dependencies-{{ .Environment.CIRCLE_WORKFLOW_ID }}
      - run:
          name: login into dockerhub
          command: docker login --username $DOCKER_USER --password $DOCKER_PW
      - run:
          name: build docker image
          command: docker build -t capstone .
      - run:
          name: tag docker image
          command: docker tag capstone ht2314/capstone:${CIRCLE_WORKFLOW_ID:0:7}
      - run:
          name: push docker image
          command: docker push ht2314/capstone:${CIRCLE_WORKFLOW_ID:0:7}
    
  create-infra:
    <<: *default-node-image
    executor: aws-cli/default
    steps:
      - install-kubectl
      - install-eksctl
      - run:
          name: create cluster
          command: |
            capstone=$(aws eks list-clusters | grep "capstone-project")
            if [[ -n "$capstone" ]]; then
                echo "capstone project already exists, skipping creatiion new cluster"
            else
                eksctl create cluster --name capstone-project --region=us-east-1
            fi
      - destroy-cluster

  deploy:
    <<: *default-node-image
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - checkout
      - install-kubectl
      - run:
          name: set up cluster config
          command: |
            aws eks --region us-east-1 update-kubeconfig --name capstone-project
      - run:
          name: update to new version
          command: |
            kubectl set image deployments/capstone-project capstone-project=ht2314/capstone:${CIRCLE_WORKFLOW_ID:0:7}

workflows:
  default:
    jobs:
      - build
      - test:
          requires: [build]
      - lint:
          requires: [build]
      - build-docker-image:
          requires: [lint, test]
      - create-infra:
          requires: [build-docker-image]
      - deploy:
          requires: [create-infra]
